name: Release

on:
    workflow_dispatch: 
    push:
        branches:
            - main
        paths-ignore:
            - '**/README.md'
            - '**/poetry.lock'
            - '**/pyproject.toml'
            - '**/requirements.txt'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set outputs
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                tag_name: test
                name: "Ayo v${{ vars.VERSION }}-${{ steps.vars.outputs.sha_short }}"
                body: ${{ github.event.head_commit.message }}
                draft: false
                prerelease: true

            - name: Delete Old Pre-Release
              uses: sgpublic/delete-release-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                pre-release-keep-count: 1
                pre-release-drop: true
                pre-release-drop-tag: true